# Grafana Datasources Configuration for SentientEdge
# Military-grade monitoring data sources

apiVersion: 1

datasources:
  # Prometheus - Primary metrics source
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.47.0
      cacheLevel: 'High'
      disableMetricsLookup: false
      customQueryParameters: ''
      timeInterval: '15s'

  # Loki - Log aggregation
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"

  # Jaeger - Distributed tracing
  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [
          { key: 'service.name', value: 'service' },
          { key: 'service.namespace', value: 'namespace' }
        ]
        mapTagNamesEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: true

  # Elasticsearch - For ELK stack integration
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "sentient-*"
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: "${ELASTIC_PASSWORD}"
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: "8.11.0"
      includeFrozen: false
      logMessageField: message
      logLevelField: level
      maxConcurrentShardRequests: 5

  # PostgreSQL - Database metrics (via postgres_exporter)
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: sentient_edge
    user: postgres
    secureJsonData:
      password: "${POSTGRES_PASSWORD}"
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      maxConnLifetime: 14400

  # InfluxDB - Time series data (if using for high-frequency telemetry)
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: sentient_telemetry
    user: sentient
    secureJsonData:
      password: "${INFLUXDB_PASSWORD}"
    jsonData:
      httpMode: GET
      keepCookies: []

  # TestData - For dashboard development and testing
  - name: TestData
    type: testdata
    uid: testdata
    access: proxy
    isDefault: false
    editable: true