image:
  repository: ghcr.io/your-org/sentientedge
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

env:
  APP_VERSION: "0.1.0"
  NEXT_PUBLIC_ENABLE_REALTIME: "true"

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: sentientedge.example.com
      paths:
        - path: /
          pathType: Prefix

extraEnvFromSecret: {}


