apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: sentient-edge-production

resources:
- ../../base

namespace: sentient-edge-prod

namePrefix: prod-

commonLabels:
  environment: production
  classification: military-grade

images:
- name: registry.sentientedge.military/sentient-edge/frontend
  newTag: stable
- name: registry.sentientedge.military/sentient-edge/backend
  newTag: stable

replicas:
- name: frontend
  count: 5
- name: backend
  count: 5
- name: nginx
  count: 3

patchesStrategicMerge:
- config-patch.yaml
- resource-patch.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: frontend
  path: frontend-production-patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: backend
  path: backend-production-patch.yaml

configMapGenerator:
- name: production-config
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=warn
  - METRICS_ENABLED=true
  - SECURITY_LEVEL=maximum
  - RATE_LIMIT_MAX=500
  - RATE_LIMIT_WINDOW=900000

secretGenerator:
- name: production-secrets
  type: Opaque
  files:
  - production.env